run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - gocritic
    - shadow
  disable:
    - depguard

linters-settings:
  govet:
    shadow: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - appendAssign
  errcheck:
    exclude-functions:
      - fmt.Fprintf
      - fmt.Fprintln
      - (io.Closer).Close

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
  exclude-dirs:
    - vendor
